from tkinter import *
import game

window = Tk()
window.geometry('450x250')
window.resizable(0, 0)
window.title('Rock, paper, scissors')
topFrame = Frame(window)
topFrame.pack()
bottomFrame = Frame(window)
bottomFrame.pack(side=BOTTOM)
computerLabel = Label(bottomFrame, font=('Courier', 14))
computerLabel.pack()
resultLabel = Label(bottomFrame, text='Welcome to the Rock, paper, scissors game\n', font=('Times New Roman', 18))
resultLabel.pack()
scoreLabel = Label(bottomFrame, font=('Times New Roman', 18, 'bold'))
scoreLabel.pack()
rock = PhotoImage(file='images/100x100/Rock.png')
paper = PhotoImage(file='images/100x100/Paper.png')
scissors = PhotoImage(file='images/100x100/Scissors.png')
buttonRock = Button(topFrame, height=100, width=100, command=game.button_rock_on_click, image=rock)
buttonPaper = Button(topFrame, height=100, width=100, command=game.button_paper_on_click, image=paper)
buttonScissors = Button(topFrame, height=100, width=100, command=game.button_scissors_on_click, image=scissors)
buttonRock.pack(side=LEFT)
buttonPaper.pack(side=LEFT)
buttonScissors.pack(side=LEFT)
window.mainloop()
